# Generated by Django 4.2 on 2024-11-16 23:46

from django.db import migrations, models
import shortener_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasedUrl',
            fields=[
                ('alias', models.CharField(default=shortener_app.utils.get_random_alias, max_length=8, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
